//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School_Book_Database_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class SBInventory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SBInventory()
        {
            this.SBOrders = new HashSet<SBOrder>();
        }
    
        public int BookInventoryId { get; set; }
        public string Subject { get; set; }
        public string BookName { get; set; }
        public string ExamBoardAndLevel { get; set; }
        public string BookType { get; set; }
        public string BookSatus { get; set; }
        public Nullable<int> QuantityInStock { get; set; }
        public string Notes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SBOrder> SBOrders { get; set; }
    }
}
