//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School_Book_Database_App
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SchoolBooksDBEntities : DbContext
    {
        public SchoolBooksDBEntities()
            : base("name=SchoolBooksDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SBInventory> SBInventories { get; set; }
        public virtual DbSet<SBOrder> SBOrders { get; set; }
        public virtual DbSet<Student> Students { get; set; }
    }
}
