//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School_Book_Database_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int StudentID { get; set; }
        public Nullable<int> OrderBooksID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> SchoolYear { get; set; }
        public string Subjects { get; set; }
        public string ExamBoardAndLevel { get; set; }
        public Nullable<bool> BooksRecieved { get; set; }
        public string BookStatus { get; set; }
    
        public virtual SBOrder SBOrder { get; set; }
    }
}
